name: Create GitHub Release

on:
  push:
    tags:
      - 'production*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Get the latest tag
      - name: Get the latest tag
        id: get_latest_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      # Step 3: Gather commit messages since the previous tag
      - name: Gather commit messages
        id: gather_commits
        run: |
          previous_tag=$(git describe --tags --abbrev=0 HEAD^)
          commit_messages=$(git log $previous_tag..HEAD --pretty=format:"%s")
          echo "commit_messages=$commit_messages" >> $GITHUB_ENV

      # Step 4: Create a GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: ${{ env.tag }}
          body: ${{ env.commit_messages }}
          draft: false
          prerelease: false
