name: Create GitHub Release

on:
  push:
    tags:
      - 'production*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get the latest tag
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0)
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Get previous tag
        run: |
          # Attempt to get the previous tag safely
          previous_tag_commit=$(git rev-list --tags --skip=1 --max-count=1)
          if [ -n "$previous_tag_commit" ]; then
            previous_tag=$(git describe --tags --abbrev=0 "$previous_tag_commit")
          else
            previous_tag=""
          fi
          echo "previous_tag=$previous_tag" >> $GITHUB_ENV

      - name: Get commit messages
        run: |
          # If there is no previous tag, get all commit messages; otherwise, get commits between tags
          if [ -z "$previous_tag" ]; then
            commit_messages=$(git log --pretty=format:"%s")
          else
            commit_messages=$(git log $previous_tag..$latest_tag --pretty=format:"%s")
          fi
          echo "commit_messages=$commit_messages" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.latest_tag }}
          release_name: ${{ env.latest_tag }}
          body: ${{ env.commit_messages }}